apiVersion: v1
data:
  initgit.sh: |
    cd /tmp
    until wget -q --spider  {{.Values.yuuvis.git.protocol}}://$GITSERVER
    do 
        echo waiting for git
        sleep 11
    done
    
    echo git clone
    
    if git clone  {{.Values.yuuvis.git.protocol}}://$GITUSER:$GITPASSWORD@$GITURL --branch $GITBRANCH; 
    then
        echo "git branch ${GITBRANCH} already exists"
        cd $GITNAME
    else
        git clone  {{.Values.yuuvis.git.protocol}}://$GITUSER:$GITPASSWORD@$GITURL
        cd $GITNAME
        echo "creating new ${GITBRANCH}"
        echo git checkout -b
        git checkout -b  $GITBRANCH
    fi
    
    if [ -f application-es.yml ]; 
    then 
        echo application-es.yml exists 
        exit 0
    fi
    
    cp /yuuvis/data/*.yml .
    
    echo "create realm"
    eval export OAUTH2PATH=$(pwd)/application-oauth2.yml
    java -jar /yuuvis/init.jar
    
    mkdir system
    
    cd system
    cp /yuuvis/data/system/*.xml .
    cp /yuuvis/data/system/*.json .
    cd ..
    
    git config --local user.email {{.Values.yuuvis.git.email}}
    git config --local user.name {{.Values.yuuvis.git.user}}
    git add .
    git commit -m "init config"
    
    echo 'git push'    
    if git push origin {{.Values.yuuvis.git.branch}} &> /dev/null
    then
        echo 'push sucessful'
    else
        echo 'push unsucessful'
        exit 1
    fi    
kind: ConfigMap
metadata:
  name: initcommitconfigmap
