yuuvis:
  image:
    imagePullPolicy: Always
    imagePullSecret: yuuvisorg
    dockerRegistry: docker.yuuvis.org
  livenessProbe:
    initialDelaySeconds: 300
    periodSeconds: 30
    timeoutSeconds: 10
  readinessProbe:
    initialDelaySeconds: 0
    periodSeconds: 30
    timeoutSeconds: 5
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
    runAsNonRoot: true
  configservice:
    url: http://system/config
  renditionservice:
    dockerImage: yuuvis/renditionservice:4.21.4
    profiles: prod
    instances: 1
    java:
      maxHeap: -Xmx2048m -XX:+ExitOnOutOfMemoryError
    pdb:
      # pdb requires instances > 1 and minAvailable < instances,
      # otherwise draining nodes will deadlock!
      enabled: false

      # set `minAvailable: null` if you want to use maxUnavailable instead
      minAvailable: 1
    nodeSelector: {}
    priorityClassName: ""
    tolerations: []
    nodeAffinity: {}
    podAffinity: {}
    podAntiAffinity: {}
  renditionrepository:
    dockerImage: yuuvis/rendition-repository:2.3.0
    profiles: prod,storage,dbs
    instances: 1
    java:
      options: -Xmx256m -XX:+ExitOnOutOfMemoryError
    pdb:
      # pdb requires instances > 1 and minAvailable < instances,
      # otherwise draining nodes will deadlock!
      enabled: false

      # set `minAvailable: null` if you want to use maxUnavailable instead
      minAvailable: 1
    nodeSelector: {}
    priorityClassName: ""
    tolerations: []
    nodeAffinity: {}
    podAffinity: {}
    podAntiAffinity: {}
  renditiontextworker:
    dockerImage: yuuvis/textextraction-worker-service:4.21.4
    instances: 1
    profiles: prod
    java:
      options: -Xmx1024m -XX:+ExitOnOutOfMemoryError
    yuuvis:
      url: http://authentication-internal
      renditionrepository:
        url: http://renditionrepository
      user:
      # if createnewsecret is  set, the values from
      # user and password will be used to create a secret with
      # the name secretname
      # keys in the secret are 'tenant', 'user' and 'password'
      # and optionally (if createuser.enabled 'true') 'email', 'keycloakadmin' and 'keycloakadminpassword'
        createnewsecret: true
        secretname: textextractionworker
        tenant: myfirsttenant
        username: changeme
        password: changeme
        createuser: 
          enabled: true
          image: yuuvis/helper/create-cross-tenant-user:24_v3
          # required in keycloak
          # if missing keycloak will show a form to add the address
          # this will break the yuuvis login
          email: email@example.com
          keycloak:
            url: http://keycloak-http.infrastructure/auth
            admin: keycloak
            adminpassword: changeme

    pdb:
      # pdb requires instances > 1 and minAvailable < instances,
      # otherwise draining nodes will deadlock!
      enabled: false

      # set `minAvailable: null` if you want to use maxUnavailable instead
      minAvailable: 1
    nodeSelector: {}
    priorityClassName: ""
    tolerations: []
    nodeAffinity: {}
    podAffinity: {}
    podAntiAffinity: {}

initContainer:
  command: "until wget -q --spider http://system/manage/health; do echo waiting for configservice; sleep 11; done;"
  image: library/busybox
  tag: 1.36
  imagePullPolicy: IfNotPresent
