{{- if .Values.yuuvis.client.architect.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: architect
  name: architect
spec:
  replicas: {{.Values.yuuvis.client.architect.instances}}
  selector:
    matchLabels:
      name: architect
  template:
    metadata:
      labels:
        name: architect
    spec:
      automountServiceAccountToken: false
      {{- if or .Values.yuuvis.client.architect.nodeAffinity .Values.yuuvis.client.architect.podAffinity .Values.yuuvis.client.architect.podAntiAffinity }}
      affinity:
        {{- with .Values.yuuvis.client.architect.nodeAffinity }}
        nodeAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.client.architect.podAffinity }}
        podAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.client.architect.podAntiAffinity }}
        podAntiAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      containers:
      - image: {{.Values.yuuvis.image.dockerRegistry}}/{{.Values.yuuvis.client.architect.dockerImage}}
        imagePullPolicy: {{ .Values.yuuvis.image.imagePullPolicy }}
        name: architect
        ports:
        - containerPort: 80
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        {{- if .Values.yuuvis.client.architect.resources }}
        resources: {{- toYaml .Values.yuuvis.client.architect.resources | nindent 10 }}
        {{- end }}
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      imagePullSecrets:
      - name: {{.Values.yuuvis.image.imagePullSecret }}
      restartPolicy: Always
      {{- with .Values.yuuvis.client.architect.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.yuuvis.client.architect.priorityClassName }}
      priorityClassName: {{ .Values.yuuvis.client.architect.priorityClassName }}
      {{- end }}
      {{- with .Values.yuuvis.client.architect.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: {{.Values.yuuvis.securityContext.fsGroup}}
        runAsGroup: {{.Values.yuuvis.securityContext.runAsGroup}}
        runAsUser: {{.Values.yuuvis.securityContext.runAsUser}}
        runAsNonRoot: {{.Values.yuuvis.securityContext.runAsNonRoot}}
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - emptyDir: {}
        name: tmp
{{- end }}      