{{- if .Values.yuuvis.renditiontextworker.yuuvis.user.createnewsecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.yuuvis.renditiontextworker.yuuvis.user.secretname }}
type: Opaque
data:
  tenant: {{ .Values.yuuvis.renditiontextworker.yuuvis.user.tenant | b64enc | quote }}
  user: {{ .Values.yuuvis.renditiontextworker.yuuvis.user.username | b64enc | quote }}
  password: {{ .Values.yuuvis.renditiontextworker.yuuvis.user.password | b64enc | quote }}
{{- if and .Values.yuuvis.renditiontextworker.yuuvis.user.createnewsecret  .Values.yuuvis.renditiontextworker.yuuvis.user.createuser.enabled }}
  email: {{ .Values.yuuvis.renditiontextworker.yuuvis.user.createuser.email | b64enc | quote }}
  keycloadadmin: {{ .Values.yuuvis.renditiontextworker.yuuvis.user.createuser.keycloak.admin | b64enc | quote }}
  keycloakadminpassword: {{ .Values.yuuvis.renditiontextworker.yuuvis.user.createuser.keycloak.adminpassword | b64enc | quote }}
{{- end -}}
{{- end -}}
