apiVersion: v2
appVersion: "1.0"
description: umbrella chart with examples for infrastructure components of an yuuvis API installation
             infrastructure components include a database, an identity provider, storage etc.
             this chart is for demo use only 
             do not use this chart for production 
name: infrastructure
version: 0.16.1
dependencies:
- name: minio
  version: ^5.3.0
  repository: https://charts.min.io/
  condition: minio.enabled
- name: keycloakx
  version: ^2.5.1
  repository: https://codecentric.github.io/helm-charts/
  condition: keycloak.enabled
  alias: keycloak
- name: redis
  version: ^20.4.0
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: postgresql
  version: ^15.5.38
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: rabbitmq
  version: ^15.1.0
  repository: https://charts.bitnami.com/bitnami 
  condition: rabbitmq.enabled
- name: gitea
  version: ^9.6.1
  repository: https://dl.gitea.io/charts/
  condition: gitea.enabled
